#Title joka tulee kun pelaaja joinaa, Värit on '&' merkillä!
JoinTitle: '&a&lTervetuloa Tutopiaan!'
#alempi teksti titlessä
JoinSubTitle: '&6Pidä Hauskaa'
#numero, kuinka monta minecraft tickiä että title tulee näytölle
JoinTitleFadeIn: 20
#numero (minecraft ticks), kuinka kauan title pysyy näytöllä
JoinTitleStay: 60
#numero, kuinka monta minecraft tickiä että title lähtee näytöltä
JoinTitleFadeOut: 15
